Japan's Shinto fix
Abkwreu/divergences pull request #119
Opened 2022-12-04 21:04 UTC by EliteNinjaX

Japan and her puppets are now Shinto, and some pops have changed to created better balance, lore and colour for East Asia.
Please disregard and delete the other pull request for Japan and Venice as I was still learning how they worked.

2022-12-07 19:39 UTC, MadJamez requested changes
Remove color changes for now. Mughals green like in FF.
Best to make a different branch for the other color changes.

2022-12-08 00:19 UTC, Xerodoeht commented
The pop changes are definitely pretty questionable at points as well, I noticed you added, a lot of Chinese Catholics? I think you should definitely wait on doing that until there is a justification for them being there

2022-12-19 00:26 UTC, Xerodoeht commented on localization/english/dvg_countries_l_english.yml
> + JIA_ADJ:0 "Jiangxi" #No idea tbh
Could use gan?

2022-12-19 00:26 UTC, Xerodoeht commented on localization/english/dvg_flavor_china_l_english.yml
> + law_china_feudal_armies_desc:0 "Originally developed by the Yuan, the Ming and latter Shun inherited the Wei-Suo system to help guard it's borders, by creating military households along the frontier
Is officer-latron correct here?

2022-12-19 00:27 UTC, Xerodoeht commented on localization/english/dvg_countries_l_english.yml
> + JIA_ADJ:0 "Jiangxi" #No idea tbh
Though Jiangxi is fine by the way, you don't need to change it

2023-01-25 19:43 UTC, MadJamez requested changes
Not sure if the review description is correct. Can you maybe update it, and if this includes multiple features, please split it up over multiple reviews.

2023-03-14 06:17 UTC, closed without merging